name: chat_client
version: 0.1.0
publish_to: none
description: Chat client
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  socket_io_client: ^2.0.2
  get: 4.6.5
  google_fonts: any
  path_provider: ^2.0.15
  get_storage: 2.1.1
  intl: 0.18.1
  soundpool: 2.3.0
  http: 0.13.0
  soundpool_web: 2.2.0
  firebase_core: 2.15.0
  firebase_messaging: 14.6.5
  cached_network_image: 3.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/audios/
  uses-material-design: true

