// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCLWmggqordR56iJtvhFfA5miilB8Tej-Q",
    authDomain: "chatme-d4b25.firebaseapp.com",
    projectId: "chatme-d4b25",
    storageBucket: "chatme-d4b25.appspot.com",
    messagingSenderId: "213611714815",
    appId: "1:213611714815:web:53b95b247f1895b25854ca",
    measurementId: "G-211TSYCVP0",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFvvqLNlAQPhw5r6VX2jNITh6_PffbMMU',
    appId: '1:213611714815:android:64e697b4ef09fa055854ca',
    messagingSenderId: '213611714815',
    projectId: 'chatme-d4b25',
    storageBucket: 'chatme-d4b25.appspot.com',
  );
}
