// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFvvqLNlAQPhw5r6VX2jNITh6_PffbMMU',
    appId: '1:213611714815:android:64e697b4ef09fa055854ca',
    messagingSenderId: '213611714815',
    projectId: 'chatme-d4b25',
    storageBucket: 'chatme-d4b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtOfNEH7FJ0TzE-pw9ztck9Fd6c4J2a44',
    appId: '1:213611714815:ios:9c200a1f3706c66a5854ca',
    messagingSenderId: '213611714815',
    projectId: 'chatme-d4b25',
    storageBucket: 'chatme-d4b25.appspot.com',
    iosClientId: '213611714815-e85omtgtgtgrpimomvksvvcke3kt3k9r.apps.googleusercontent.com',
    iosBundleId: 'com.edoaurahman.chatClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtOfNEH7FJ0TzE-pw9ztck9Fd6c4J2a44',
    appId: '1:213611714815:ios:e3d0dd74e0406b265854ca',
    messagingSenderId: '213611714815',
    projectId: 'chatme-d4b25',
    storageBucket: 'chatme-d4b25.appspot.com',
    iosClientId: '213611714815-r3pa68jehl0eac2ukuh4bq34onvd7oj3.apps.googleusercontent.com',
    iosBundleId: 'com.edoaurahman.chatClient.RunnerTests',
  );
}
